"use client";
import { useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";

type Row=Record<string,string|number|null>;
const API="/api/organizacao-em-harmonia/filhos-corrente/agendamento-piloto/relatorios";
function csv(rows:Row[]){if(!rows.length)return "";const h=Object.keys(rows[0]);const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;return [h.map(esc).join(";"),...rows.map(r=>h.map(k=>esc(r[k])).join(";"))].join("\r\n");}
function download(name:string,body:string,type:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
export default function GestaoPage(){
 const [kind,setKind]=useState("atendimentos"),[date,setDate]=useState(""),[person,setPerson]=useState(""),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState("");
 async function load(){setError("");const {data}=await supabaseBrowser.auth.getSession();const token=data.session?.access_token;if(!token){setError("Sessão não localizada.");return;}const q=new URLSearchParams({kind});if(date)q.set("date",date);if(person)q.set("person",person);const r=await fetch(`${API}?${q}`,{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();if(!r.ok){setError(j.error||"Falha ao gerar relatório.");return;}setRows(j.rows||[]);}
 const exportCsv=()=>download(`tucxa-${kind}.csv`,"\ufeff"+csv(rows),"text/csv;charset=utf-8");
 const exportExcel=()=>{if(!rows.length)return;const h=Object.keys(rows[0]);const html=`<table><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr>${rows.map(r=>`<tr>${h.map(k=>`<td>${String(r[k]??"")}</td>`).join("")}</tr>`).join("")}</table>`;download(`tucxa-${kind}.xls`,html,"application/vnd.ms-excel");};
 return <main className="min-h-screen bg-[#F7FAF2] p-4 text-[#10251C]"><section className="mx-auto max-w-6xl"><a href="../" className="font-black underline">← Voltar</a><h1 className="mt-4 text-3xl font-black">Gestão · Relatórios</h1><div className="mt-4 grid gap-2 rounded-2xl bg-white p-4 sm:grid-cols-4"><select value={kind} onChange={e=>setKind(e.target.value)} className="rounded-xl border p-3"><option value="atendimentos">Atendimentos</option><option value="consulentes">Consulentes</option><option value="entidades">Entidades / Cavalinhos</option></select><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border p-3"/><input value={person} onChange={e=>setPerson(e.target.value)} placeholder="Consulente" className="rounded-xl border p-3"/><button onClick={()=>void load()} className="rounded-xl bg-[#123D2C] p-3 font-black text-white">Consultar</button></div>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</p>}<div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>window.print()} className="rounded-xl border bg-white px-4 py-2 font-black">PDF / Imprimir</button><button onClick={exportCsv} className="rounded-xl border bg-white px-4 py-2 font-black">CSV</button><button onClick={exportExcel} className="rounded-xl border bg-white px-4 py-2 font-black">Excel</button><button onClick={()=>window.open("https://sheets.new","_blank","noopener,noreferrer")} className="rounded-xl border bg-white px-4 py-2 font-black">Abrir Google Sheets</button></div><div className="mt-3 overflow-auto rounded-2xl bg-white p-3">{rows.length?<table className="min-w-full text-sm"><thead><tr>{Object.keys(rows[0]).map(h=><th key={h} className="border-b p-2 text-left">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{Object.keys(rows[0]).map(h=><td key={h} className="border-b p-2">{String(r[h]??"")}</td>)}</tr>)}</tbody></table>:<p className="p-4 font-semibold text-slate-500">Faça uma consulta para visualizar o relatório.</p>}</div></section></main>;
}
