export type TucxaGuideScreenshot = {
  id: string;
  fileNames: string[];
  label: string;
};

export type TucxaGuideNode = {
  id: string;
  eyebrow: string;
  title: string;
  summary: string;
  why?: string;
  outcome?: string;
  href?: string;
  ctaLabel?: string;
  accessNote?: string;
  steps?: string[];
  attention?: string[];
  screenshotId?: string;
  children?: TucxaGuideNode[];
};

const TUCXA = "/solucoes/organizacao-em-harmonia/tucxa";
const FILHO = `${TUCXA}/filho-da-corrente`;
const FILHO_PAINEL = `${FILHO}/painel`;
const CONSULENTE = `${TUCXA}/consulente`;
const CONSULENTE_PAINEL = `${CONSULENTE}/painel`;
const CLIENTE = "/solucoes/organizacao-em-harmonia/cliente";

export const TUCXA_GUIDE_SCREENSHOT_BASE =
  "/organizacao-em-harmonia/tucxa/guia";

export const tucxaGuideScreenshots: TucxaGuideScreenshot[] = [
  {
    id: "principal-topo",
    fileNames: ["01-principal-topo-mobile.png"],
    label: "Página principal do Tucxa em Harmonia",
  },
  { id: "filho-inicio", fileNames: ["03-filho-corrente-inicio-mobile.png"], label: "Página do Filho da Corrente" },
  { id: "filho-primeiro-acesso", fileNames: ["04-filho-primeiro-acesso-mobile.png"], label: "Primeiro acesso do Filho da Corrente" },
  { id: "filho-login", fileNames: ["05-filho-login-mobile.png"], label: "Login do Filho da Corrente" },
  { id: "filho-painel", fileNames: ["06-filho-painel-mobile.png"], label: "Painel do Filho da Corrente" },
  { id: "filho-atendimento", fileNames: ["07-filho-atendimento-mobile.png"], label: "Atendimento em Harmonia do Filho da Corrente" },
  {
    id: "filho-orientacoes",
    fileNames: ["08-filho-orientacoes-mobile-01.png", "08-filho-orientacoes-mobile-02.png"],
    label: "Orientações práticas do Filho da Corrente",
  },
  {
    id: "filho-agendamentos",
    fileNames: ["09-filho-acolhimento-agendamentos-mobile-01.png", "09-filho-acolhimento-agendamentos-mobile-02.png"],
    label: "Acolhimento e agendamentos do Filho da Corrente",
  },
  {
    id: "filho-consulta",
    fileNames: ["10-filho-consulta-agendamentos-mobile-01.png", "10-filho-consulta-agendamentos-mobile-02.png"],
    label: "Consulta de agendamentos / Recepção",
  },
  {
    id: "filho-escuta",
    fileNames: ["11-filho-escuta-mobile-01.png", "11-filho-escuta-mobile-02.png"],
    label: "Escuta dos Filhos da Corrente",
  },
  { id: "filho-agenda", fileNames: ["12-filho-agenda-viva-mobile.png"], label: "Agenda Viva no painel do Filho da Corrente" },
  {
    id: "filho-atualizar",
    fileNames: ["13-filho-atualizar-dados-mobile-01.png", "13-filho-atualizar-dados-mobile-02.png"],
    label: "Atualização de cadastro do Filho da Corrente",
  },
  { id: "filho-corrente", fileNames: ["14-filho-corrente-em-dia-mobile.png"], label: "Corrente em Dia no painel do Filho da Corrente" },
  {
    id: "cursos-gestao",
    fileNames: ["15-cursos-gestao-mobile-01.png", "15-cursos-gestao-mobile-02.png"],
    label: "Gestão de Cursos — curso, aulas, alunos e Agenda Viva",
  },
  { id: "consulente-inicio", fileNames: ["17-consulente-inicio-mobile.png"], label: "Página do Consulente / Filho de Fora" },
  { id: "consulente-login", fileNames: ["19-consulente-login-mobile.png"], label: "Login do Consulente" },
  { id: "consulente-painel", fileNames: ["20-consulente-painel-mobile.png"], label: "Painel do Consulente" },
  { id: "consulente-atendimento", fileNames: ["21-consulente-atendimento-mobile.png"], label: "Atendimento em Harmonia do Consulente" },
  { id: "consulente-agendar", fileNames: ["22-consulente-agendar-mobile.png"], label: "Tela de agendamento do Consulente" },
  { id: "agenda-publica", fileNames: ["23-agenda-viva-publica-mobile.png"], label: "Agenda Viva pública" },
  { id: "sementinha-inicio", fileNames: ["24-sementinha-inicio-mobile.png"], label: "Página principal do Sementinha em Harmonia" },
  { id: "sementinha-despensa", fileNames: ["25-sementinha-despensa-viva-mobile.png"], label: "Despensa Viva" },
  { id: "sementinha-transparencia", fileNames: ["26-sementinha-transparencia-mobile.png"], label: "Prestação de Contas / Transparência do Sementinha" },
];

export const tucxaSystemGuide: TucxaGuideNode = {
  id: "inicio",
  eyebrow: "Guia Vivo do Tucxa em Harmonia",
  title: "O que você precisa resolver agora?",
  summary: "Você não precisa conhecer o sistema inteiro. Escolha seu objetivo e o guia leva você, passo a passo, até a tela certa.",
  why: "O sistema foi organizado para reduzir procura em mensagens antigas, retrabalho de cadastro e dúvida sobre qual caminho seguir.",
  outcome: "Em poucos toques, você entende onde entrar, o que fazer e o que deve acontecer depois.",
  href: TUCXA,
  ctaLabel: "Abrir página principal",
  screenshotId: "principal-topo",
  children: [
    {
      id: "consulente",
      eyebrow: "Quero ser atendido",
      title: "Consulente / Filho de Fora",
      summary: "Comece pelo acolhimento, faça seu cadastro quando necessário, consulte a agenda e acompanhe o que é seu.",
      why: "Você não precisa conhecer as regras internas para descobrir o próximo passo.",
      outcome: "Chegar ao atendimento mais preparado, com data e orientação claras.",
      screenshotId: "consulente-inicio",
      children: [
        {
          id: "consulente-conhecer",
          eyebrow: "Primeiro contato",
          title: "Quero entender como funciona antes de me cadastrar",
          summary: "Use a página de acolhimento para conhecer o atendimento e decidir o próximo passo.",
          href: `${CONSULENTE}/novo`,
          ctaLabel: "Abrir acolhimento",
          steps: [
            "Leia a explicação inicial sobre acolhimento e atendimento.",
            "Escolha a opção indicada para agendar, alterar um atendimento ou contribuir de forma identificada.",
            "Quando o sistema solicitar identificação, siga para cadastro ou login.",
          ],
          outcome: "Você entende o caminho antes de fornecer dados ou escolher uma data.",
          screenshotId: "consulente-inicio",
        },
        {
          id: "consulente-cadastro",
          eyebrow: "Primeiro acesso",
          title: "Ainda não tenho cadastro",
          summary: "Faça um cadastro único para não repetir suas informações a cada novo atendimento.",
          href: `${CONSULENTE}/cadastro`,
          ctaLabel: "Abrir cadastro",
          steps: [
            "Informe os dados solicitados na tela.",
            "Confira telefone e e-mail antes de enviar.",
            "Finalize o cadastro e siga a orientação de acesso exibida pelo sistema.",
          ],
          attention: ["Use dados da própria pessoa que será atendida para evitar duplicidade de cadastro."],
          outcome: "Seus próximos acessos ficam ligados ao mesmo cadastro.",
        },
        {
          id: "consulente-login",
          eyebrow: "Já tenho cadastro",
          title: "Entrar no meu espaço",
          summary: "Use o login para consultar apenas o que pertence ao seu cadastro.",
          href: `${CONSULENTE}/login`,
          ctaLabel: "Abrir login",
          steps: [
            "Informe o dado de acesso solicitado.",
            "Digite sua senha.",
            "Se não lembrar a senha, use a recuperação disponível na própria tela.",
          ],
          outcome: "Você chega ao painel com Agenda Viva, Atendimento em Harmonia e contribuição identificada.",
          screenshotId: "consulente-login",
        },
        {
          id: "consulente-painel",
          eyebrow: "Área logada",
          title: "Escolher o que quero fazer no painel",
          summary: "O painel reúne os caminhos de uso frequente para evitar que você precise decorar endereços.",
          href: CONSULENTE_PAINEL,
          ctaLabel: "Abrir painel",
          screenshotId: "consulente-painel",
          children: [
            {
              id: "consulente-atendimento",
              eyebrow: "Atendimento em Harmonia",
              title: "Chegar preparado e organizar minha solicitação",
              summary: "Consulte primeiro as orientações e depois siga para o agendamento quando precisar.",
              href: `${CONSULENTE_PAINEL}/atendimento`,
              ctaLabel: "Abrir Atendimento",
              steps: [
                "Abra Orientações quando quiser revisar como se preparar.",
                "Abra Acolhimento e Atendimento quando quiser consultar datas e organizar sua solicitação.",
                "Siga os botões da própria tela até a confirmação.",
              ],
              outcome: "Você reduz dúvidas antes do dia do atendimento.",
              screenshotId: "consulente-atendimento",
            },
            {
              id: "consulente-acervo-vivo",
              eyebrow: "Acervo Vivo",
              title: "Encontrar um livro, uma trilha ou um conteúdo para estudar",
              summary: "Use o Acervo Vivo com o mesmo cadastro de Filho de Fora/Consulente; não é preciso criar outro cadastro para a biblioteca.",
              href: `${CONSULENTE_PAINEL}/atendimento/acervo-vivo`,
              ctaLabel: "Abrir Acervo Vivo",
              steps: [
                "Abra o Acervo Vivo.",
                "Pesquise pelo assunto, título ou autor que deseja estudar.",
                "Consulte trilhas e disponibilidade dos títulos.",
                "Quando houver uma ação disponível para seu perfil, siga a orientação mostrada na própria tela.",
              ],
              outcome: "Você encontra caminhos de estudo sem depender de saber previamente qual livro procurar.",
            },
            {
              id: "consulente-agendar",
              eyebrow: "Agendamento",
              title: "Escolher uma possibilidade apresentada pelo sistema",
              summary: "O calendário mostra as opções compatíveis com as regras atuais do atendimento.",
              href: `${CONSULENTE}/agendar`,
              ctaLabel: "Abrir agendamento",
              steps: [
                "Escolha o período disponível.",
                "Toque em uma data apresentada pelo sistema.",
                "Confira horário e demais informações antes de confirmar.",
                "Finalize e guarde a confirmação exibida.",
              ],
              attention: ["Se uma data não estiver disponível, escolha outra opção apresentada pelo próprio sistema."],
              outcome: "Você agenda sem precisar calcular manualmente quais dias são permitidos.",
              screenshotId: "consulente-agendar",
            },
            {
              id: "consulente-agenda-viva",
              eyebrow: "Agenda Viva",
              title: "Ver o que está programado",
              summary: "Consulte o calendário para se organizar com antecedência.",
              href: `${CONSULENTE_PAINEL}/agenda-viva`,
              ctaLabel: "Abrir Agenda Viva",
              steps: ["Escolha o período.", "Toque na data desejada.", "Leia os detalhes disponíveis para aquele dia."],
              outcome: "Você encontra informação de agenda sem procurar em mensagens antigas.",
              screenshotId: "agenda-publica",
            },
            {
              id: "consulente-contribuicao",
              eyebrow: "Corrente em Dia",
              title: "Fazer uma contribuição identificada",
              summary: "Use seu acesso para vincular a contribuição ao seu cadastro quando desejar.",
              href: `${CONSULENTE}/contribuicao?tipo=identificada`,
              ctaLabel: "Abrir contribuição",
              steps: ["Abra a contribuição identificada.", "Confira os dados apresentados.", "Siga as instruções de envio e confirmação da tela."],
              outcome: "A contribuição pode ser tratada de forma organizada e identificada.",
            },
          ],
        },
      ],
    },
    {
      id: "filho",
      eyebrow: "Sou Filho da Corrente",
      title: "Participar da rotina do Tucxa com clareza",
      summary: "Use seu acesso para consultar agenda, orientações, funções, cursos, cadastro e Corrente em Dia.",
      why: "A informação certa no mesmo lugar reduz dependência de memória, planilhas paralelas e mensagens soltas.",
      outcome: "Você sabe o que precisa fazer antes, durante e depois de cada compromisso.",
      screenshotId: "filho-inicio",
      children: [
        {
          id: "filho-primeiro-acesso",
          eyebrow: "Primeiro acesso",
          title: "Ainda não tenho acesso",
          summary: "Faça o cadastro em etapas e envie seus dados para validação.",
          href: `${FILHO}/primeiro-acesso`,
          ctaLabel: "Abrir primeiro acesso",
          steps: [
            "Informe seus dados na primeira etapa.",
            "Confira as informações e vínculos solicitados na etapa seguinte.",
            "Envie para validação.",
            "Acompanhe o status até a liberação do acesso.",
          ],
          attention: ["Escolha somente funções e vínculos que correspondem à sua atuação real no Tucxa."],
          outcome: "Depois da validação, seu acesso fica ligado às funções que você realmente exerce.",
          screenshotId: "filho-primeiro-acesso",
        },
        {
          id: "filho-login",
          eyebrow: "Já tenho acesso",
          title: "Entrar como Filho da Corrente",
          summary: "Entre para acessar as áreas e atalhos liberados para o seu perfil.",
          href: `${FILHO}/login`,
          ctaLabel: "Abrir login",
          steps: ["Informe seu dado de acesso.", "Digite a senha.", "Use a recuperação de senha se precisar."],
          outcome: "Você chega ao painel com as opções compatíveis com seu cadastro.",
          screenshotId: "filho-login",
        },
        {
          id: "filho-painel",
          eyebrow: "Painel",
          title: "Escolher meu próximo passo",
          summary: "O painel reúne seus principais acessos e atalhos pessoais em uma única tela.",
          href: FILHO_PAINEL,
          ctaLabel: "Abrir painel",
          screenshotId: "filho-painel",
          children: [
            {
              id: "filho-atendimento",
              eyebrow: "Atendimento em Harmonia",
              title: "Preparar, acolher, consultar e aprender",
              summary: "Este espaço organiza o que precisa ser consultado antes, durante e depois do atendimento e conecta cuidado, formação e conhecimento.",
              href: `${FILHO_PAINEL}/atendimento`,
              ctaLabel: "Abrir Atendimento",
              screenshotId: "filho-atendimento",
              children: [
                {
                  id: "filho-orientacoes",
                  eyebrow: "Orientações práticas",
                  title: "Revisar como servir com segurança",
                  summary: "Consulte as orientações antes de atuar quando tiver qualquer dúvida de procedimento.",
                  href: `${FILHO_PAINEL}/atendimento/orientacoes`,
                  ctaLabel: "Abrir Orientações",
                  steps: ["Abra a orientação necessária.", "Leia o checklist correspondente.", "Volte ao Atendimento em Harmonia para continuar."],
                  outcome: "Você reduz improviso e chega mais preparado ao trabalho.",
                  screenshotId: "filho-orientacoes",
                },
                {
                  id: "filho-acolhimento",
                  eyebrow: "Acolhimento e agendamentos",
                  title: "Escolher somente os dias que fazem sentido para sua atuação",
                  summary: "Use a área de agendamentos para organizar sua participação conforme as opções liberadas.",
                  href: `${FILHO_PAINEL}/atendimento/agendamentos`,
                  ctaLabel: "Abrir agendamentos",
                  steps: ["Escolha o grupo ou tipo disponível.", "Consulte os dias apresentados.", "Confirme somente os compromissos que correspondem à sua atuação."],
                  outcome: "A agenda fica mais confiável para todos que dependem dela.",
                  screenshotId: "filho-agendamentos",
                },
                {
                  id: "filho-recepcao",
                  eyebrow: "Recepção",
                  title: "Localizar e acompanhar os atendimentos previstos",
                  summary: "Quando a função estiver liberada no seu cadastro, use a consulta para apoiar o acolhimento.",
                  href: `${FILHO_PAINEL}/atendimento/consultar-agendamentos?from=atendimento`,
                  ctaLabel: "Abrir consulta",
                  accessNote: "A opção depende da função/permissão de Recepção.",
                  steps: ["Abra a consulta.", "Pesquise pelos critérios disponíveis.", "Confira a pessoa, data e atendimento antes de agir.", "Use a edição somente quando a tela e sua permissão permitirem."],
                  outcome: "A Recepção encontra mais rápido quem precisa ser acolhido.",
                  screenshotId: "filho-consulta",
                },
                {
                  id: "filho-escuta",
                  eyebrow: "Escuta dos Filhos da Corrente",
                  title: "Registrar uma pergunta para que ela não se perca no caminho",
                  summary: "Use a Escuta quando o assunto precisa ser registrado e acompanhado.",
                  href: `${FILHO_PAINEL}/escuta-em-harmonia`,
                  ctaLabel: "Abrir Escuta",
                  steps: ["Abra a Escuta.", "Informe o assunto e a mensagem.", "Revise antes de enviar.", "Acompanhe o retorno conforme as opções da tela."],
                  outcome: "Perguntas importantes deixam de depender de uma conversa isolada.",
                  screenshotId: "filho-escuta",
                },
                {
                  id: "filho-acervo-vivo",
                  eyebrow: "Acervo Vivo — Biblioteca do Tucxa",
                  title: "Descobrir o que estudar e acompanhar meus livros",
                  summary: "Pesquise o acervo, descubra trilhas e use o mesmo cadastro do Filho da Corrente para acessar a biblioteca.",
                  href: `${FILHO_PAINEL}/atendimento/acervo-vivo`,
                  ctaLabel: "Abrir Acervo Vivo",
                  steps: [
                    "Abra o Acervo Vivo.",
                    "Use a busca quando já souber o que procura ou comece pelas trilhas quando quiser uma orientação de estudo.",
                    "Abra o título para consultar os dados e a disponibilidade.",
                    "Acompanhe reservas e empréstimos conforme as opções liberadas no seu acesso.",
                  ],
                  outcome: "O acervo deixa de ser apenas uma estante e passa a ajudar você a encontrar o próximo conteúdo de estudo.",
                },
                {
                  id: "filho-cursos-atalho",
                  eyebrow: "Gestão de Cursos",
                  title: "Ir da organização do curso até a presença em aula",
                  summary: "Quando sua função permitir, abra a Gestão de Cursos para administrar curso, aulas, professores e alunos.",
                  href: `${CLIENTE}/cursos`,
                  ctaLabel: "Abrir Gestão de Cursos",
                  accessNote: "A opção depende da função/permissão cadastrada.",
                  outcome: "O curso fica conectado à agenda e à presença, sem controles separados.",
                  screenshotId: "cursos-gestao",
                },
              ],
            },
            {
              id: "filho-agenda",
              eyebrow: "Agenda Viva",
              title: "Conferir meus próximos compromissos e o calendário do Tucxa",
              summary: "Use a agenda antes de assumir um novo compromisso ou para revisar o que já está programado.",
              href: `${FILHO_PAINEL}/agenda-viva`,
              ctaLabel: "Abrir Agenda Viva",
              steps: ["Escolha o período.", "Toque na data.", "Leia os eventos e compromissos disponíveis."],
              outcome: "Você se organiza com uma visão única do calendário.",
              screenshotId: "filho-agenda",
            },
            {
              id: "filho-atualizar",
              eyebrow: "Meu cadastro",
              title: "Manter meus dados, funções e vínculos atualizados",
              summary: "Atualize somente o que mudou para que agenda, comunicação e acessos continuem corretos.",
              href: `${FILHO_PAINEL}/atualizar-dados`,
              ctaLabel: "Atualizar meus dados",
              steps: ["Confira seus dados.", "Altere somente o necessário.", "Revise funções e vínculos quando a tela solicitar.", "Envie a atualização para o fluxo indicado."],
              outcome: "O sistema consegue orientar você com base em informações mais confiáveis.",
              screenshotId: "filho-atualizar",
            },
            {
              id: "filho-corrente-em-dia",
              eyebrow: "Corrente em Dia",
              title: "Acompanhar contribuição e informações financeiras disponíveis para meu perfil",
              summary: "Use esta área para consultar situação, enviar informações e acessar análises quando sua função permitir.",
              href: `${FILHO_PAINEL}/corrente-em-dia`,
              ctaLabel: "Abrir Corrente em Dia",
              steps: ["Abra Corrente em Dia.", "Confira a situação mostrada no topo.", "Escolha contribuição, financeiro ou análises conforme as opções liberadas."],
              outcome: "Contribuição e informação financeira deixam de depender de controles paralelos.",
              screenshotId: "filho-corrente",
            },
            {
              id: "filho-preferencias",
              eyebrow: "Preferências",
              title: "Escolher quais avisos quero ver ao entrar",
              summary: "Ajuste os avisos para manter o painel útil sem repetir informações que você já conhece.",
              href: `${FILHO_PAINEL}/configuracoes`,
              ctaLabel: "Abrir preferências",
              steps: ["Abra Preferências.", "Ative ou desative os avisos disponíveis.", "Salve as escolhas."],
              outcome: "Sua entrada no sistema fica mais objetiva.",
            },
          ],
        },
      ],
    },
    {
      id: "acervo-vivo",
      eyebrow: "Acervo Vivo — Biblioteca do Tucxa",
      title: "Encontrar conhecimento para o momento que estou vivendo",
      summary: "Livros, trilhas e conteúdos do Tucxa conectados à Biblioteca, Clube do Livro, Grupo de Estudos e Curso Preparatório.",
      why: "Quem quer estudar nem sempre sabe qual título procurar. O Acervo Vivo organiza o conhecimento por assunto, jornada e atividade do Tucxa, sem criar um novo cadastro para quem já está na Base Única.",
      outcome: "Você consegue descobrir, localizar e acompanhar conteúdos com menos dependência de planilhas, mensagens ou memória de quem sabe onde cada material está.",
      children: [
        {
          id: "acervo-filho",
          eyebrow: "Filho da Corrente",
          title: "Usar o Acervo Vivo com meu acesso atual",
          summary: "Entre pela área do Filho da Corrente para pesquisar, consultar trilhas e acompanhar ações disponíveis para o seu cadastro.",
          href: `${FILHO_PAINEL}/atendimento/acervo-vivo`,
          ctaLabel: "Abrir Acervo Vivo",
          steps: [
            "Entre como Filho da Corrente.",
            "Abra Atendimento em Harmonia.",
            "Escolha Acervo Vivo.",
            "Pesquise um conteúdo ou comece por uma trilha de estudos.",
          ],
          outcome: "Não é necessário manter um cadastro separado de leitor.",
        },
        {
          id: "acervo-consulente",
          eyebrow: "Filho de Fora / Consulente",
          title: "Usar a biblioteca sem repetir meu cadastro",
          summary: "Quem já possui cadastro como Consulente usa a mesma identidade para acessar o Acervo Vivo.",
          href: `${CONSULENTE_PAINEL}/atendimento/acervo-vivo`,
          ctaLabel: "Abrir Acervo Vivo",
          steps: [
            "Entre como Filho de Fora/Consulente.",
            "Abra Atendimento em Harmonia.",
            "Escolha Acervo Vivo.",
            "Pesquise livros, trilhas e conteúdos disponíveis.",
          ],
          outcome: "O histórico da biblioteca fica ligado à pessoa já cadastrada na Base Única.",
        },
        {
          id: "acervo-gestao",
          eyebrow: "Gestão do Acervo",
          title: "Cuidar do catálogo, exemplares, circulação e trilhas",
          summary: "A área de gestão reúne o trabalho dos responsáveis pela Biblioteca do Tucxa.",
          href: `${CLIENTE}/acervo-vivo`,
          ctaLabel: "Abrir gestão do Acervo Vivo",
          accessNote: "A gestão depende da função/permissão cadastrada para a pessoa.",
          steps: [
            "Abra a gestão do Acervo Vivo.",
            "Escolha a atividade: catálogo, exemplares, empréstimos/reservas, inventário, conteúdos ou trilhas.",
            "Revise as informações antes de salvar alterações.",
          ],
          outcome: "O acervo físico e os conteúdos de formação passam a compartilhar uma referência organizada.",
        },
      ],
    },
    {
      id: "cursos",
      eyebrow: "Cursos em Harmonia",
      title: "Do planejamento da aula à presença dos alunos",
      summary: "Curso, agenda, professores, convites e chamada fazem parte do mesmo fluxo.",
      why: "Quando cada etapa fica em um lugar diferente, aumenta o risco de conflito, convite perdido e chamada incompleta.",
      outcome: "A equipe organiza o curso antes da aula e o professor acompanha a presença no momento certo.",
      screenshotId: "cursos-gestao",
      children: [
        {
          id: "cursos-gestao",
          eyebrow: "Organização do curso",
          title: "Criar ou selecionar um curso e montar o cronograma",
          summary: "Comece pelo curso para que aulas, professores e alunos fiquem ligados ao contexto correto.",
          href: `${CLIENTE}/cursos`,
          ctaLabel: "Abrir Gestão de Cursos",
          accessNote: "Requer função/permissão de gestão de cursos.",
          steps: [
            "Crie um curso novo ou selecione um curso existente.",
            "Cadastre as aulas com data e horário.",
            "Associe o professor quando aplicável.",
            "Use a Agenda Viva para conferir conflitos antes de confirmar.",
            "Pesquise alunos e envie os convites disponíveis.",
          ],
          attention: ["Em curso concluído, preserve o histórico e use as opções de consulta disponibilizadas pela tela."],
          outcome: "O cronograma passa a ser a referência para professor, aluno e agenda.",
          screenshotId: "cursos-gestao",
        },
        {
          id: "cursos-convite",
          eyebrow: "Aluno",
          title: "Aceitar o convite para participar do curso",
          summary: "O aluno usa o link de convite para confirmar sua participação.",
          steps: ["Abra o link recebido por WhatsApp ou e-mail.", "Confira o curso e as aulas previstas.", "Escolha participar ou recusar.", "Depois de aceitar, use os acessos orientados pelo sistema."],
          outcome: "A lista do curso passa a refletir quem realmente aceitou participar.",
        },
        {
          id: "cursos-professor",
          eyebrow: "Professor",
          title: "Gerar o código e conferir a chamada da aula",
          summary: "Na Sala de aula, o professor seleciona a aula, gera o código e acompanha os alunos que aceitaram o curso.",
          href: `${FILHO_PAINEL}/cursos`,
          ctaLabel: "Abrir Sala de aula",
          accessNote: "Requer função/permissão de Professor para o curso correspondente.",
          steps: [
            "Selecione a aula correta.",
            "Gere o código de presença e mostre somente aos alunos presentes.",
            "Acompanhe os registros feitos pelos alunos.",
            "Quando necessário, marque Presente, Ausente ou Justificada manualmente.",
          ],
          outcome: "A presença fica registrada no mesmo contexto do curso e da aula.",
        },
      ],
    },
    {
      id: "agenda",
      eyebrow: "Agenda Viva",
      title: "Antes de marcar, veja o que já está acontecendo",
      summary: "Use o calendário como visão compartilhada para consultar compromissos e evitar conflito.",
      why: "Uma agenda confiável reduz remarcações, sobreposição e dependência de mensagens para descobrir datas.",
      outcome: "Você escolhe datas com mais segurança e entende o que existe em cada dia.",
      href: `${TUCXA}/agenda-viva`,
      ctaLabel: "Abrir Agenda Viva",
      screenshotId: "agenda-publica",
      steps: ["Abra o calendário.", "Escolha o período desejado.", "Toque em uma data para consultar os detalhes.", "Se estiver planejando uma atividade, confira conflitos antes de confirmar."],
    },
    {
      id: "gestao",
      eyebrow: "Organização / Gestão",
      title: "Manter cadastro, agenda, validações e rotinas coerentes",
      summary: "As telas administrativas organizam a base que sustenta os acessos e as áreas usadas pelas pessoas.",
      why: "Uma Base Única bem cuidada evita que cada solução crie seu próprio cadastro e suas próprias regras.",
      outcome: "Funções, agenda e permissões ficam mais previsíveis para quem usa o sistema.",
      children: [
        {
          id: "gestao-base-unica",
          eyebrow: "Base Única",
          title: "Organizar envolvidos, funções, grupos, vínculos, entidades e localidades",
          summary: "Use a Base Única como referência central para as demais áreas.",
          href: `${CLIENTE}/base-unica`,
          ctaLabel: "Abrir Base Única",
          accessNote: "Esta etapa depende da validação e do acesso liberado pelo administrador do Tucxa em Harmonia.",
          steps: ["Abra a Base Única.", "Escolha o cadastro que precisa manter.", "Revise antes de salvar para não duplicar pessoas ou funções."],
          outcome: "As demais áreas passam a consumir a mesma referência de cadastro.",
        },
        {
          id: "gestao-agenda",
          eyebrow: "Agenda Viva administrativa",
          title: "Cadastrar, aprovar e consultar eventos em um só fluxo",
          summary: "Use as opções administrativas da Agenda Viva para manter o calendário confiável.",
          href: `${CLIENTE}/agenda-viva`,
          ctaLabel: "Abrir Agenda Viva administrativa",
          accessNote: "Esta etapa depende da validação e do acesso liberado pelo administrador do Tucxa em Harmonia.",
          steps: ["Escolha cadastros, eventos, calendário, aprovações, presenças ou configurações.", "Faça a alteração necessária.", "Confira o calendário depois de salvar."],
          outcome: "Quem consulta a agenda encontra informação mais consistente.",
        },
        {
          id: "gestao-validacoes",
          eyebrow: "Validações",
          title: "Revisar solicitações antes de liberar alterações e acessos",
          summary: "Use a validação para manter a qualidade da Base Única e das permissões.",
          href: `${CLIENTE}/validacoes`,
          ctaLabel: "Abrir Validações",
          accessNote: "Esta etapa depende da validação e do acesso liberado pelo administrador do Tucxa em Harmonia.",
          steps: ["Abra a fila de validações.", "Confira a solicitação e os dados relacionados.", "Aprove ou trate conforme as opções da tela."],
          outcome: "O acesso deixa de ser liberado automaticamente sem revisão quando a regra exige validação.",
        },
        {
          id: "gestao-acervo-vivo",
          eyebrow: "Acervo Vivo administrativo",
          title: "Manter catálogo, exemplares, circulação, conteúdos e trilhas",
          summary: "Use a gestão do Acervo Vivo para organizar a Biblioteca do Tucxa e suas conexões com formação e estudo.",
          href: `${CLIENTE}/acervo-vivo`,
          ctaLabel: "Abrir Acervo Vivo administrativo",
          accessNote: "Esta etapa depende da função/permissão liberada para a gestão do Acervo Vivo.",
          steps: [
            "Abra o Acervo Vivo.",
            "Escolha o processo que precisa manter.",
            "Revise título, exemplar, pessoa, conteúdo ou trilha antes de concluir.",
          ],
          outcome: "Biblioteca, trilhas e conteúdos ficam organizados na mesma Base de Harmonia.",
        },
        {
          id: "gestao-corrente",
          eyebrow: "Corrente em Dia administrativo",
          title: "Organizar contribuições, lançamentos, conciliação e prestação de contas",
          summary: "As telas financeiras separam registro, conferência e apresentação para reduzir retrabalho.",
          href: `${CLIENTE}/corrente-em-dia`,
          ctaLabel: "Abrir Corrente em Dia administrativo",
          accessNote: "Esta etapa depende da validação e do acesso liberado pelo administrador do Tucxa em Harmonia.",
          steps: ["Escolha o processo financeiro que precisa executar.", "Registre ou confira os dados.", "Use reconciliação e prestação de contas conforme a etapa do processo."],
          outcome: "A informação financeira fica mais rastreável e preparada para consulta.",
        },
      ],
    },
    {
      id: "sementinha",
      eyebrow: "Sementinha em Harmonia",
      title: "Acompanhar o cuidado da entrada até a entrega",
      summary: "O Sementinha reúne visão, frentes assistenciais e transparência em um espaço próprio.",
      why: "Informação organizada ajuda quem cuida a decidir melhor e ajuda quem colabora a enxergar o caminho do cuidado.",
      outcome: "Estoque, validade, entregas e transparência podem evoluir sem depender de planilhas isoladas.",
      href: `${TUCXA}/sementinha`,
      ctaLabel: "Abrir Sementinha",
      screenshotId: "sementinha-inicio",
      children: [
        {
          id: "sementinha-visao",
          eyebrow: "Visão",
          title: "Entender o propósito e escolher a opção certa",
          summary: "Comece pela página do Sementinha para conhecer o que já está disponível e o que ainda está em evolução.",
          href: `${TUCXA}/sementinha`,
          ctaLabel: "Abrir Sementinha",
          steps: ["Leia a visão inicial.", "Vá até as opções disponíveis.", "Escolha Despensa Viva, Bazar ou a alternativa que corresponda à sua necessidade."],
          outcome: "Você chega à opção certa sem precisar saber seu endereço.",
          screenshotId: "sementinha-inicio",
        },
        {
          id: "sementinha-despensa",
          eyebrow: "Despensa Viva",
          title: "Consultar e atualizar o estoque com atenção a lote e validade",
          summary: "A Despensa Viva organiza produtos para ajudar a priorizar o que precisa ser usado primeiro.",
          href: `${TUCXA}/sementinha/despensa-viva`,
          ctaLabel: "Abrir Despensa Viva",
          accessNote: "As opções de atualização dependem da função/subfunção cadastrada na Base Única.",
          steps: ["Entre com seu acesso quando solicitado.", "Consulte os produtos e lotes.", "Confira validade antes de registrar movimentação.", "Na saída, priorize o lote que vence primeiro quando a regra da tela indicar."],
          outcome: "A equipe reduz perda por validade e enxerga melhor o que está disponível para as ações.",
          screenshotId: "sementinha-despensa",
        },
        {
          id: "sementinha-transparencia",
          eyebrow: "Prestação de Contas",
          title: "Entender receitas, despesas, resultado e saldo do Sementinha",
          summary: "Use a transparência para acompanhar o período com uma leitura preparada para consulta.",
          href: `${TUCXA}/sementinha/transparencia`,
          ctaLabel: "Abrir Prestação de Contas",
          steps: ["Escolha o período disponível.", "Leia o resumo da competência.", "Consulte os grupos e itens quando precisar entender a composição."],
          outcome: "Quem acompanha consegue relacionar recursos e continuidade das ações assistenciais.",
          screenshotId: "sementinha-transparencia",
        },
      ],
    },
  ],
};

export function findTucxaGuideScreenshot(id?: string) {
  if (!id) return undefined;
  return tucxaGuideScreenshots.find((item) => item.id === id);
}

export function findTucxaGuideNode(id: string, root: TucxaGuideNode = tucxaSystemGuide): TucxaGuideNode | undefined {
  if (root.id === id) return root;
  for (const child of root.children ?? []) {
    const result = findTucxaGuideNode(id, child);
    if (result) return result;
  }
  return undefined;
}
